site_name: Sorse Engine docs
site_url: 'https://blocksnmore.github.io/Sorse-Engine/'
base_url: '/Sorse-Engine/'
use_directory_urls: true
theme:
    palette:
        scheme: slate
    name: material
    custom_dir: overrides
markdown_extensions:
    - pymdownx.highlight:
          linenums: true
    - pymdownx.superfences
